# Generated by Django 5.1.1 on 2024-10-07 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('fecha_contrato', models.DateField(help_text='Fecha del inicio del contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.BooleanField(default=False)),
                ('luz', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('telefonia', models.BooleanField(default=False)),
                ('cable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(help_text='Fecha de emision de la factura')),
                ('fecha_vencimineto', models.DateField(help_text='Fecha de vencimiento de la factura')),
                ('valor', models.BigIntegerField(default=0)),
                ('estado', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('contrato_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('verificacion', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(help_text='Fecha del pago de la factura')),
                ('factura_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='servicios_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicios'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='usuario_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario'),
        ),
    ]
