# Generated by Django 5.1.1 on 2024-10-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('numero_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('R', 'Reportado')], max_length=1)),
                ('fecha_contrato', models.DateField(help_text='Fecha del contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=254)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('U', 'Usuario')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la factura')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la factura')),
                ('estado', models.CharField(choices=[('P', 'Pagada'), ('PE', 'Pendiente'), ('V', 'Vencida')], default='PE', max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('numero_contrato_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contratos')),
                ('servicio_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('metodo_pago', models.IntegerField(choices=[(1, 'Transferencia Bancaria'), (2, 'Tarjeta de crédito'), (3, 'Tarjeta de débito'), (4, 'Efectivo'), (5, 'Billetera electrónica'), (6, 'Cheque'), (7, 'Código QR')])),
                ('fecha_pago', models.DateField(help_text='Fecha del pago de la factura')),
                ('facturas_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturas')),
                ('usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='usuario_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario'),
        ),
        migrations.CreateModel(
            name='Usuarios_servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiene_servicio', models.BooleanField(default=False)),
                ('servicios_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicios')),
                ('usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario')),
            ],
        ),
    ]
