# Generated by Django 5.1.1 on 2024-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Supendido'), (3, 'Inactivo'), (4, 'Finalizado')]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pagada'), (2, 'Pendiente'), (3, 'Vencida')]),
        ),
    ]
